# Generated by Django 5.0.1 on 2025-06-03 04:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_creator_job_description_job_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('job_link', models.URLField(help_text='Application link')),
                ('location', models.CharField(help_text='Job location', max_length=200)),
                ('experience', models.CharField(help_text='Required experience level', max_length=100)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], help_text='Type of job', max_length=100)),
                ('salary', models.CharField(help_text='Salary range', max_length=100)),
                ('posted_date', models.DateField(default=django.utils.timezone.now, help_text='Date when job was posted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='User who created this job post', on_delete=django.db.models.deletion.CASCADE, related_name='post_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Job',
                'verbose_name_plural': 'Post Jobs',
                'ordering': ['-posted_date', '-created_at'],
            },
        ),
    ]
