# Generated by Django 5.0.1 on 2025-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_postjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjobs',
            name='experience',
            field=models.CharField(blank=True, help_text='Required experience level', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postjobs',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], help_text='Type of job', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postjobs',
            name='location',
            field=models.CharField(blank=True, help_text='Job location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postjobs',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary range', max_length=100, null=True),
        ),
    ]
